start sections and components
0xHabitat/docs pull request #4
Opened 2022-02-09 16:25 UTC by tjvsx

2022-02-17 13:01 UTC, mwaa commented
@tjvsx Looking into the code but currently concerned about the load speed of the landing page. Resources are heavy, lighthouse is unable to process page

2022-02-17 16:27 UTC, tjvsx commented
@mwaa I agree, I think it's time to focus on performance. My first thoughts are
- reduce size of png banner/cover photo
- use lazy loading
- simplify/lighten the code
- remove animation's 'complete' even listener after use
... I will research some additional ways, but would love to hear your thoughts and ideas on this

2022-02-21 15:18 UTC, mwaa commented
> @mwaa I agree, I think it's time to focus on performance. My first thoughts are
> 
> * reduce size of png banner/cover photo
> * use lazy loading
> * simplify/lighten the code
> * remove animation's 'complete' even listener after use
>   ... I will research some additional ways, but would love to hear your thoughts and ideas on this

This should be sufficient i guess. 
If images are lazy loaded then should be better

2022-02-21 15:20 UTC, mwaa commented on docusaurus.config.js
> +  // plugins: [
If you evaluate the plugin is not needed then rather than comment more code it would be preferable to remove entirely

2022-02-21 16:23 UTC, mwaa requested changes
Good work @tjvsx 
Minor changes but otherwise performance has improved considerably. 

- Can you change the blog to point to substack for now 
- Can you add SEO optimization https://docusaurus.io/docs/next/seo  basically page meta for layout page is only thing missing

2022-02-21 16:23 UTC, mwaa commented on package.json
>      "@cmfcmf/docusaurus-search-local": "^0.10.0",
In the config this is commented out, if not needed also remove the dependency

2022-02-21 16:23 UTC, mwaa commented on sidebars.js
> +  // indexSidebar: [
Remove code instead of comments if not needed

2022-02-21 16:23 UTC, mwaa commented on src/css/custom.css
> +/* html[data-theme='dark'] {
Same clean up all code comments if not needed or move to reference developer doc if you need to maintain color reference in future

2022-02-21 16:23 UTC, mwaa commented on src/css/custom.css
> +  background: url('https://ik.imagekit.io/habitat/emoji-sunrise-over-mountains.png?ik-sdk-version=javascript-1.4.3&updatedAt=1645306385939') no-repeat;
Nice use of CDN. 
Are the images to the CDN compressed for web?
Not sure if you have still retained a local copy of the images folder and add in that folder a README.md file that the images have been uploaded to imagekit CDN to assist future developers when they want to change an image

2022-02-21 16:23 UTC, mwaa commented on src/pages/sections/InfoSection.js
> +            <Optimism className={clsx('info_img', styles.svg_img)} height={100} width={100}/>
Quick question what do you think of className={`info_img ${styles.svg_img}`}?
Instead of using clsx and remove it as a dependency in an effort to reduce dependencies?

2022-02-21 16:23 UTC, mwaa commented on src/pages/sections/InfoSection.js
> +            <Optimism className={clsx('info_img', styles.svg_img)} height={100} width={100}/>
This would apply on each usage of clsx.
Just a question need you opinion if you feel its worth using clsx

2022-02-23 20:25 UTC, tjvsx commented on src/pages/sections/InfoSection.js
> +            <Optimism className={clsx('info_img', styles.svg_img)} height={100} width={100}/>
this was what docusaurus was using on their template landing page. there may be an underlying reason for its use.

2022-02-24 08:56 UTC, mwaa requested changes

2022-02-24 08:56 UTC, mwaa commented on docusaurus.config.js
> +  url: 'https://habitat/',
Tiny missed url should be https://0xhabitat.org/

2022-02-24 08:56 UTC, mwaa commented on src/pages/index.js
> +      description="Description will go into a meta tag in <head />">
Can we change this description or its overloaded by something in the config?

2022-02-24 08:56 UTC, mwaa commented on src/pages/sections/InfoSection.js
> +            <Optimism className={clsx('info_img', styles.svg_img)} height={100} width={100}/>
Cool wee can keep for now

2022-03-05 17:03 UTC, merged